name: myenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - six
    - accelerate
    - transformers>=4.25.1
    - ftfy==6.1.1
    - scipy==1.9.0
    - tensorboard==2.11.2
    - Jinja2==3.1.2
    - datasets==2.9.0
    - diffusers
    - compel
    - wandb
    - scikit-image
    - scikit-learn
    - requests==2.26.0
    - chardet==4.0.0
    - boto3
    - deepface
    - face_recognition
    - glob2
    - ninja
    - xformers

